site_name: Sodero Documents
site_url: https://docs.sodero.io/
theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: "Inter"
    code: "JetBrains Mono"
  palette:
    - scheme: slate
      primary: black
      accent: white
  features:
    - navigation.expand
    - navigation.path 
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
extra:
  version:
    provider: mike
  comments:
    provider: giscus
    options:
      repo: Sodero-labs/docs
      repo_id: R_kgDOQiK7fQ  
      category: Q&A   
      category_id: DIC_kwDOQiK7fc4C3JkV
      mapping: pathname
      strict: 0
      reactions_enabled: 1
      emit_metadata: 0
      input_position: bottom
      theme: dark
      lang: en
extra_css:
  - styles/layout.css
  - styles/color.css
  - styles/font.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Stellar X:
    - What is Stellar X: stellarx/what_is_stellarx/index.md
    - Quick Start: stellarx/quick_start/index.md
    - Tutorials:
      - Stellar Designer:
        - Introduction: stellarx/tutorials/stellar_designer/introduction/index.md
        - Create New Robot:
          - Step 1. Robot Structure: stellarx/tutorials/stellar_designer/robot_structure/index.md
          - Step 2. Robot System Parameters: stellarx/tutorials/stellar_designer/configure_system_parameters/index.md
          - Step 3. Actuator Mapping: stellarx/tutorials/stellar_designer/map_actuators/index.md
          - Step 4. Virtual Verification: stellarx/tutorials/stellar_designer/verify_configuration/index.md
        - Start from Templates: stellarx/tutorials/stellar_designer/start_from_templates/index.md

      - Stellar Motion Studio:
        - About Stellar Motion Studio: stellarx/tutorials/stellar_motion_studio/about_stellar_motion_studio/index.md
        - Home: stellarx/tutorials/stellar_motion_studio/home/index.md
        - Tool: stellarx/tutorials/stellar_motion_studio/tool/index.md
        - Pose: stellarx/tutorials/stellar_motion_studio/pose/index.md
        - Motion: stellarx/tutorials/stellar_motion_studio/motion/index.md
      - Simulation & Virtual Control:
        - Virtual Control Overview: stellarx/tutorials/simulation/virtual_control_overview/index.md
        - Isaac Sim:
          - Introduction: stellarx/tutorials/simulation/introduction/index.md
          - Extension Installation: stellarx/tutorials/simulation/extension_installation/index.md
          - Robot Setup: stellarx/tutorials/simulation/robot_setup/index.md
    - User Guide:
      - Remote Control:
        - Understanding Remote Control: stellarx/user_guide/remote_control/understanding_remote_control/index.md
      - APIS: stellarx/user_guide/apis/index.md
      - Stellar Designer:
        - Setup:
          - Robot Structure: stellarx/user_guide/stellar_designer/robot_structure
          - Robot System Parameters: stellarx/user_guide/stellar_designer/robot_system_parameters
          - Actuator Mapping: stellarx/user_guide/stellar_designer/actuator_mapping

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - glightbox